### ISSUE TITLE
Add "autoUpdate" to VCS for Database-level installs

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-addin#118]
Add ability for the addin to "call home" and then update itself when installed as a database-level addin. This would be useful for reducing overhead for more casual developers that just want to focus on their database and not have the headache of needing to update ancillary components.

I suggest adding this to modAPI (#117), or at least making the update function available.

**Comment by hecon5** [comment]
Actually, after some thought; it's probably best this reside in a "calling" side module. Based on experience from building my front end updater, it's not possible to have a file update itself without exiting the file; something that requires an external shell script to update the file you've currently got open. Since the point is to be quiet and not require any user knowledge (except where needed), it'd be best to put this in a helper VCS module. 

I'm in the process of writing one to take advantage of the API; I'll add one to auto-update the addin and post it when I'm done (though the auto-update will probably not be within the next bit).

**Comment by joyfullservice** [comment]
We might consider adding this update functionality in a new module called `modUpdate`. This could check for updates on GitHub, and offer to install them. For security reasons any update should require user approval, and there will also need to be an option to set the frequency to check for updates. (ie. daily, 7 days, 30 days, or never.) It would be very important to have the option to turn off any "call home" functionality, and require the user's explicit consent before enabling an update check or install.

I am not shooting down this idea at all. I have actually been thinking about implementing some type of update check, but we just need to be very careful to maintain trust with our users and prevent any type of security vulnerability where the program could be changed without the user's knowledge.

**Comment by hecon5** [comment]
Absolutely agree on not foisting it without notice. I meant more that the updater has to be outside the referenced file, because Access (at least in my environment) won't let you update the file you have open. 

I think the "check for version updates" and "let user know" can/should be in the modUpdate, the actual updating routine (if calling from a database without it installed at the application level) has to reside in the referencing file (unless you know of a super secret way to do this...I've not discovered it).

**Comment by joyfullservice** [comment]
> I think the "check for version updates" and "let user know" can/should be in the modUpdate, the actual updating routine (if calling from a database without it installed at the application level) has to reside in the referencing file (unless you know of a super secret way to do this...I've not discovered it).

There are a couple approaches I have successfully used for this. To update the current database file, I have adapted [this approach](http://blog.nkadesign.com/2008/05/06/ms-access-restarting-the-database-programmatically/) of creating and executing a temporary batch file that watches for the lock file to disappear when the database is closed.

For library databases, you can actually update the library file while the main database is open, but you need to reopen the database to clear the in-memory reference to the library and load the updated one. (You can't just remove the reference after the library is loaded.)

I also have another module that I use as part of our internal deployment system that maintains current versions of shared library databases and deploys the applications as auto-updating click-once installers. It works really nice in our environment with 40+ Access applications/integrations. You can see more details at https://github.com/joyfullservice/msaccess-devops.

**Comment by hecon5** [comment]
Thanks for the link to the batch file; I do something very similar, though I wasn't watching for the lock file to be removed, I'll add that; currently I just waited a bit longer to reduce race collisions.

**Comment by hecon5** [comment]
Perhaps the way to begin this is a simple prompt that detects if a user has "checked for updates" in the last x time (user settable?standard value) of ~4weeks?

- Clicked the "Check for Updates" button on the frmMain.
- The version they're running is newer than the 4 weeks
- disabled updates

I'm not really familiar with how github handles the version/release web APIs, but just having them click on the button to take them to the version page may suffice for now.

**Comment by hecon5** [comment]
I think with the way the ribbon works now (download latest version button), and how we don't want to make phone home tools (especially in high sec environments), this feature isn't the way to go.
