### ISSUE TITLE
New database should be closed and reopened after build

### ISSUE THREAD

**Issue by joyfullservice** [joyfullservice/msaccess-vcs-addin#237]
Certain properties like the database icon, theme assignment and navigation pane groups are not fully loaded until after the new database is closed and reopened. I would like to add this in as an automatic step in the build process.

The close and reopen should also bypass any startup code or functions in the host database. (Rename `autoexec` macro, and hold down shift while opening.)

**Comment by joyfullservice** [comment]
It turns out that this is trickier than I was anticipating... If you close the current database, you also end any running code, including the add-in itself. The long-term solution is probably going to be building out a better way of caching the build state and giving multiple entry points back into the build function after restarting the build process. 

I am bumping this out to the 4.0 release due to the added complexity involved.

**Comment by hecon5** [comment]
Could also use a script, like the "open after install" option during install does.

**Comment by joyfullservice** [comment]
Restarting the code works fine with the API timer, like we currently use in other parts of the code, it is more a matter of building in the functionality to correctly resume a partial build process. (I have some ideas on how to do this, it was just more than I had time for at the moment.)

**Comment by hecon5** [comment]
Is this related to c7f9d1eec78df8408822bdbec2f7d2978c23b8a3?
