### ISSUE TITLE
MS Feedback Portal and making Access more VCS friendly

### ISSUE THREAD

**Issue by Indigo744** [joyfullservice/msaccess-vcs-addin#287]
Hello y'all 😸 

Microsoft released a [new portal to gather feedbacks from their users](https://feedbackportal.microsoft.com/feedback/forum/818e3b49-e61b-ec11-b6e7-0022481f8472) (replacing their UserVoice that went dark a year ago).

When I saw [this blog article](https://nolongerset.com/version-control-friendly-access-request/) asking for making Access friendlier towards Version Control, I immediately thought about this wonderful tool that I use daily. And, for that matters, this blog [also recommends this very tool](https://nolongerset.com/instant-version-control/)!

In any case, you can find the proposal here: https://feedbackportal.microsoft.com/feedback/idea/cd884452-6343-ec11-a81a-6045bd78d291?page=1

Maybe we can vote and participate to help brings this idea to MS?

Of course, it's not that this tool doesn't do the job. And I take the opportunity to thank @joyfullservice again for all this work. But would it be cool if MS addresses directly this issue and bring Access to the 21th century?

Have a nice day!

**Comment by joyfullservice** [comment]
@Indigo744 - Thanks for bringing this to my attention. I added my vote to Mike's suggestion. 👍  While I don't really expect Microsoft to implement this in the near future, it is encouraging to see the interest in version control among the Access development community.

**Comment by hecon5** [comment]
@joyfullservice @Indigo744 should this be closed? It's 3 years old, and only tangentially related to this Addin. Perhaps a link on the [Wiki?](https://github.com/joyfullservice/msaccess-vcs-addin/wiki)?

**Comment by Indigo744** [comment]
@hecon5 yeah I don't mind closing it. It was just to help raise awareness... 🥲
