### ISSUE TITLE
Potential Fix for Case cHangEs

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-addin#299]
I recall there was a discussion a while back about stabilizing case changes from VBA's IDE, and how it was apparently random. I cannot find it now, of course, but I'm ?pretty? sure I saw it here...oh well.

I ran across this: [StackOverflow "Stop Visual Basic 6 from changing my casing"](https://stackoverflow.com/a/1078018/16107370) articles, and I was wondering if anyone else had attempted to implement it. And, secondly...is there a way to handle this with the Addin?

I'm attempting to implement it on one of my projects now, but before I got too far, wondered if anyone else had tried this? Previously, we'd tried camelCase, PascalCase, and yet it STILL keeps happing, so we're going this route to see what we can accomplish this way.

**Comment by joyfullservice** [comment]
- See also: #227

**Comment by hecon5** [comment]
For reference: https://nolongerset.com/pascalcase-all-the-things/

**Comment by hecon5** [comment]
I'm closing this, as it's not really a bug in VCS, and it'll stay here if someone searches online.
