### ISSUE TITLE
Version 4.0 Development Progress

### ISSUE THREAD

**Issue by joyfullservice** [joyfullservice/msaccess-vcs-addin#301]
This issue is to track the overall status of the upcoming version 4.0 release. In addition to some things discussed in issues, we are wanting to track the implementation of the index-based change tracking and merge functionality for each type of object.

|  Name                       |             Index                 |              Merge               |           IsModified              |              Hash                |
| --- | :---: | :---: | :---: | :---: |
|clsDbDocument          | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbForm                  | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbHiddenAttribute | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbImexSpec            | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbMacro                 | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbModule               | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbNavPaneGroup    | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbProject                 | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbProjProperty        | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbProperty              | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbQuery                  | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbRelation               | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbReport                 | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbSavedSpec           | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbSharedImage       | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbTableDataMacro  | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbTableDef              | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbTheme                 | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbVbeForm             | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbVbeProject          | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
|clsDbVbeReference      | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |

IsModified: For simple json source objects, this is typically a comparison of the content hash with the hash stored in the index from the last export. For more complex objects like macros, it checks the modified date with the one in the index. For forms and reports which use VBA code, it checks the date as well as a hash of the VBA source.

### High Priority Issues

- #306
- #233
- #297

**Comment by hecon5** [comment]
@joyfullservice should this be tied to the [4.0 milestone? ](https://github.com/joyfullservice/msaccess-vcs-integration/milestone/2)

**Comment by hecon5** [comment]
how close are we to 4.x release as main? Seems like it might have a case of "ooh shiny" and perhaps we should pause additional features, fix bugs, and kick it out the door? :D

**Comment by joyfullservice** [comment]
We are very close at this point. I was wanting to finish the refactoring to split object layout from VBA, and just wrapped that up this week. I will probably push out a beta release later this week, then split the forms in this project. I need to also go through the Wiki and make sure it is up to date with the new options that have been added. At that point we should be ready to roll out 4.0 for general release.
