### ISSUE TITLE
Deleted imexspecs still being exported

### ISSUE THREAD

**Issue by jhgarrison** [joyfullservice/msaccess-vcs-addin#340]
Version is 3.4.20

I have deleted all saved import/export specifications via the UI.

When I run an export (full or fast-save) it is still exporting 10 imexspecs, including several that were removed over a year ago.  In VBA immediate window:

    ?codeproject.ImportExportSpecifications.count
    0 

Where are these imexspecs coming from?  Is there a way to remove them from the db "for real"?

Thanks

**Comment by joyfullservice** [comment]
There are two kinds of saved import/export specifications... The newer type accessible through the UI and object model as you highlighted in your code sample, and the legacy table-based specifications in a system table.

It sounds like you are probably dealing with some table-based specs. You can check out the code in the `clsDbImexSpec` class to see how I am reading those. You might also be interested in the [V-Tools](https://www.skrol29.com/us/vtools.php) add-in that allows you to list and manipulate these specs.

Hope that helps!  😄

**Comment by hecon5** [comment]
Is this still happening? I think this relates to #471, which was fixed I believe.
