### ISSUE TITLE
Export Selected does nothing

### ISSUE THREAD

**Issue by StuartMoors** [joyfullservice/msaccess-vcs-addin#387]
I'm trying to export a single object with Export Selected (I suspect the same problem will occur on Load Selected as well). It simply repeats the instruction to select an object first

Your code tests for the type of object selected in the Navigation Pane, testing against a UIA constant in GetSelectedNavPaneObject function.
The constant value youe test against is UIA_PaneControlTypeId (50033), but when I select a module in the Navigation Pane, the UIA type is UIA_DocumentControlTypeId (50030.)

Not surprising that no object is regarded as selected.

(Using v4.0.9)

**Comment by joyfullservice** [comment]
Hi @StuartMoors, thanks for the feedback on this! If you clone this project and build the add-in from source, I believe this issue may be fixed in the latest version. (See e27062b) 

More details are provided in the related issue #383. Let me know how it works after building from source!

**Comment by hecon5** [comment]
Is this fixed?

**Comment by StuartMoors** [comment]
I believe it is. I tried it a couple of weeks ago and I experienced no problem

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
