### ISSUE TITLE
Using XML / XSLT instead of string manipulation?

### ISSUE THREAD

**Issue by bclothier** [joyfullservice/msaccess-vcs-addin#389]
Is there a particular reason to not use MSXML2's native methods for handling XML contents?

Using the XML methods _should_ be faster than than string processing and would avoid bugs like this one addressed in this commit: https://github.com/joyfullservice/msaccess-vcs-integration/pull/388/commits/a66e4fbcb899b77e6eff1b5851ed0734c52784f5

I do see you already invested a lot of effort in optimizing string manipulation operations which are usually the biggest bottleneck but wanted to confirm if anyone had done performance tests between XML manipulation vs. string manipulation. 

FWIW, here's an example of using XSLT to control the indentation in a declarative manner. 
https://github.com/joyfullservice/msaccess-vcs-integration/blob/a66e4fbcb899b77e6eff1b5851ed0734c52784f5/Version%20Control.accda.src/modules/modSanitize.bas#L738-L774

**Comment by joyfullservice** [comment]
Thanks for the suggestion on this! I have never actually used XSL transformations, but I really like the idea of a declarative stylesheet that handles the formatting of the XML content.

On the performance side most of the time involved in running a full export on a complex database tended to be in sanitizing form objects, especially ones with embedded images or other components that added large amounts of binary data to the form definition sections. Developing and using `clsConcat` for string manipulation brought massive performance gains to the parsing process.

I would imagine you have probably seen the export log files, but at the very end of the file you can find the performance report that breaks down the performance of various operations during the export or build process. This was one of of the key tools that I used when refining and tuning the performance of exports. This would be a great place to review the difference between string manipulation and XSLT.

**Comment by bclothier** [comment]
Using a highly sourced<sup>[[citation needed]](https://en.wikipedia.org/wiki/Wikipedia:Citation_needed)</sup>, rigorous<sup>[[citation needed]](https://en.wikipedia.org/wiki/Wikipedia:Citation_needed)</sup>, peer-reviewed<sup>[[citation needed]](https://en.wikipedia.org/wiki/Wikipedia:Citation_needed)</sup> scientific study<sup>[[citation needed]](https://en.wikipedia.org/wiki/Wikipedia:Citation_needed)</sup>, I was able to determine that with version 4.0.9, I got the following times:

```
Attempt 1
Sanitize XML                  22        0.24
Format XML                    22        0.16

Attempt 2
Sanitize XML                  22        0.23
Format XML                    22        0.16
```

With version 4.0.10, I get the following times:
```
Sanitize XML                  22        0.07
Format XML                    22        0.10

Sanitize XML                  22        0.07
Format XML                    22        0.10
```

This seems to be approximately faster<sup>[[citation needed]](https://en.wikipedia.org/wiki/Wikipedia:Citation_needed)</sup>.

NOTE: the overall time, however, is either at best a wash or or at worst slightly slower for 4.0.10, due to the other changes introduced. The variance in run times were too great to properly assess the overall performance impact.

**Comment by joyfullservice** [comment]
I love the [[citation needed]](https://en.wikipedia.org/wiki/Wikipedia:Citation_needed) quotes!!  🤣  Well, I would help with the peer review except that I don't think I would quite measure up as a peer.  😄  I ran some testing this morning using a tweaked version of the sanitize function that removes the file writing and logging to keep it just down to the actual processing of the content.

Using an 86KB XML file (1500 lines) as a sample, and processing the file 1000 times, I was getting a pretty consistent output.

```vba
Public Sub TestSanitizing()

    Const cstrFile As String = "C:\...\tblSubscriptionMeta.xml"

    Dim strData As String
    Dim lngCnt As Long

    strData = ReadFile(cstrFile)
    Perf.StartTiming
    
    For lngCnt = 1 To 1000
        SanitizeXML2 (strData), False
    Next lngCnt
    
    Perf.EndTiming
    Debug.Print Perf.GetReports

End Sub
```

```
--------------------------------------------------
                PERFORMANCE REPORTS
--------------------------------------------------
Operations                    Count     Seconds
--------------------------------------------------
Sanitize XML                  1000      13.37
Format XML                    1000      16.43
--------------------------------------------------
Other Operations                        0.68
--------------------------------------------------
```

The processing time for formatting the XML was virtually identical whether I used the string manipulation or XSLT functions. Based on this I am pretty confident that we have no performance loss for taking the XSLT approach, and it gives us some other definite advantages. Great idea!!  👍

**Comment by hecon5** [comment]
I like it, too! Been away for a while (other projects ate me), but glad to see this is still being improved!

**Comment by joyfullservice** [comment]
This enhancement was a success. Closing this out as completed.
