### ISSUE TITLE
 v4.0.13-beta fails to perform a full export

### ISSUE THREAD

**Issue by akruis** [joyfullservice/msaccess-vcs-addin#407]
First of all many thanks for this great tool. :-)

I just tried to export a fairly large database using v4.0.13-beta and got an error. The same DB is exports fine on v3.4.23. I didn't test other v4.0 versions yet. The purpose of this issue is to give you feedback. For my daily work, I'm fine with v3.4.23.

![pic1](https://github.com/joyfullservice/msaccess-vcs-addin/assets/659726/25843185-01dc-49b5-8ee6-3416f38cb14f)
In IDbComponent_GetAllFromDB a key already exists in collection _m_Items_.
![pic2](https://github.com/joyfullservice/msaccess-vcs-addin/assets/659726/0763fdf9-c3ca-4d6d-b116-d5161cd38d2a)

The value of _strKey_ is `"C:\daba\zeit_access\zeit.accdb.src\nav-pane-groups.json:controlling:Nicht zugewiesene Objekte"`
_cGroup_ is newly created.

_m_Items_ contains
![pic3](https://github.com/joyfullservice/msaccess-vcs-addin/assets/659726/e4cc7f3d-4fce-434e-9f8c-3a267d8924a3)

Unfortunately I don't have a testcase, that I could provide and my VBA experience is quite limited. Please let me know, if you need additional information.

And sorry for the German Access messages.

**Comment by joyfullservice** [comment]
@akruis - Thanks for pointing out the issue here! The screen shots were very helpful to understand where the problem was occurring. I am having some difficulty producing the problem on my end, so would you be able to provide a little more information for me?

If you could add a new (temporary) query to your database, and paste in the following SQL:

```sql
SELECT MSysNavPaneGroupCategories.Name AS CategoryName, MSysNavPaneGroupCategories.Position AS CategoryPosition, MSysNavPaneGroupCategories.Flags AS CategoryFlags, MSysNavPaneGroups.Name AS GroupName, MSysNavPaneGroups.Flags AS GroupFlags, MSysNavPaneGroups.Position AS GroupPosition, MSysObjects.Type AS ObjectType, MSysObjects.Name AS ObjectName, MSysNavPaneGroupToObjects.Flags AS ObjectFlags, MSysNavPaneGroupToObjects.Icon AS ObjectIcon, MSysNavPaneGroupToObjects.Position AS ObjectPosition, MSysNavPaneGroupToObjects.Name AS NameInGroup, MSysNavPaneGroupCategories.Id AS CategoryID, MSysNavPaneGroups.Id AS GroupID, MSysNavPaneGroupToObjects.Id AS LinkID
FROM (MSysNavPaneGroupCategories INNER JOIN MSysNavPaneGroups ON MSysNavPaneGroupCategories.Id = MSysNavPaneGroups.GroupCategoryID) LEFT JOIN (MSysNavPaneGroupToObjects LEFT JOIN MSysObjects ON MSysNavPaneGroupToObjects.ObjectID = MSysObjects.Id) ON MSysNavPaneGroups.Id = MSysNavPaneGroupToObjects.GroupID
WHERE (((MSysNavPaneGroups.Name) Is Not Null) AND ((MSysNavPaneGroupCategories.Type)=4))
ORDER BY MSysNavPaneGroupCategories.Name, MSysNavPaneGroups.Name, MSysObjects.Type, MSysObjects.Name;
```

This will produce the same SQL output as the add-in uses to get a list of the navigation pane objects with their category and group information. If you could then export a couple rows from that query to an Excel spreadsheet, and attach it here, that would help me understand if the duplicate item is an issue with the query. (I am primarily wanting to compare the two rows that appear to have the same category and group name: `controlling`, `Nicht zugewiesene Objekte`.)

Thanks!

**Comment by akruis** [comment]
Hi Adam,

here is the result of the query.
[msaccess-vcs-addin_issue_407_1.xlsx](https://github.com/joyfullservice/msaccess-vcs-addin/files/11891381/msaccess-vcs-addin_issue_407_1.xlsx)

**Comment by joyfullservice** [comment]
Thanks! The output was very helpful to review. I will see if I can reproduce the issue on my end to make sure I have fully corrected the problem. (Fixing the duplicate key was easy, but I just want to make sure I don't have any logic errors in how I am building out the list of navigation pane items.)

**Comment by joyfullservice** [comment]
Thanks again for pointing this out! It did turn out to be a logic error where I was closing out the parent item in the JSON structure before closing out the child item. This caused the child item (group) to bump down to the next category, which then caused a key duplication in the VBA dictionary. I have resolved the logic error, and also added a check to only include unique keys (category:group) when getting a count of the navigation pane groups.

(P.S. I also went ahead and removed the sample file from this thread after obtaining the details I needed to recreate the issue on my end.)

**Comment by joyfullservice** [comment]
Attached is an updated copy of the add-in that includes the fix, if you wanted to try that on your database...
[Version Control_v4.0.14(dev).zip](https://github.com/joyfullservice/msaccess-vcs-addin/files/11896310/Version.Control_v4.0.14.dev.zip)

**Comment by akruis** [comment]
> Attached is an updated copy of the add-in that includes the fix, if you wanted to try that on your database... [Version Control_v4.0.14(dev).zip](https://github.com/joyfullservice/msaccess-vcs-addin/files/11896310/Version.Control_v4.0.14.dev.zip)

I just tried the fixed version. It works. Many thanks for the fix.
