### ISSUE TITLE
Error 94 "Incorrect use of Null" in Function "IDbComponent_DbObject"

### ISSUE THREAD

**Issue by monheimx9** [joyfullservice/msaccess-vcs-addin#408]
Dear joyfullservice

While exporting all sources

In the class "clsDbSharedImage"
In the Function "IDbComponent_DbObject"
Error 94 on the line:     
`m_Extension = m_Rst!Extension`
"Incorrect use of Null"

Tested on version v3.4.23 and tried on v4.0.13-beta as well
(I took some long programming vacations, the add-in was working perfectly before)
Access Version 2306  Build 16.0.16529.20100 (64Bits)

Here you can find a screenshot of the Immediate Debug Window
![Capture d’écran 2023-07-02 203716](https://github.com/joyfullservice/msaccess-vcs-addin/assets/59767686/a72901cb-fcd2-4bd8-9ef0-5b9fc2d454bb)
_"<Opération non autorisée pour ce type d'objet>" means "Operation not authorized for this object type"_
_"Vrai" means "True"_
_"Faux" means "False"_
_"Opération non valide" means "Operation not valid"_
_Translated from French_

If I can provide you additional informations feel free to ask

Otherwise I want to thank you for this amazing addin, I used it a lot last year and provided me great help in my workflow
Cheers

**Comment by joyfullservice** [comment]
Thanks for reporting this! I have wrapped the field reference in the `Nz()` function to ensure that we are assigning a string value to `m_Extension`.

**Comment by monheimx9** [comment]
Thank you for your answer, I've made the change on my side as well
But might check my comment here https://github.com/joyfullservice/msaccess-vcs-addin/commit/f8d1f229ff03900ab359d6d78388b1ddd909f9c0#r120797607
I think there is a typo

Wish you a nice day :)

**Comment by monheimx9** [comment]
Sorry, did not see https://github.com/joyfullservice/msaccess-vcs-addin/commit/60522997954f519da7f8cf5435c30fabccc850f0
Thus my previous comment is irrelevant

**Comment by joyfullservice** [comment]
Yes, you are correct. I had some other refactoring I was doing in other commits around the same time.  😄 I am hoping to build an updated beta version in the next few days, which should include this and other fixes.
