### ISSUE TITLE
Noise from `WebImagePadding[Left][Right][Top][Bottom]`?

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-addin#423]
I've been trying to figure this out for a while, to no avail, figured it's time to ask here. 

We have some form (and to a lesser degree, reports), where inexplicably, control's`WebImagePadding[Left][Right][Top][Bottom]` will change. Usually it's 1 to 2, or 2 to 3, but sometimes, the value will change from 10 to 7 or something.

This change is most often following exactly zero alterations on the form; it could just be that we rebuilt the front end and did an export. It also seems to happen when a different dev rebuilds the db on a separate machine; but it does not always happen. 

I'm not entirely sure what this field even does, so troubleshooting it (or determining if it should even make it into the change control) hasn't been easy. 

Honestly, the only place I even found a reference to the `WebImagePaddingRight` or `WebImagePaddingBottom` is a [RubberDuck Issue HERE](https://github.com/rubberduck-vba/Rubberduck/issues/1647) (except, the issue isn't talking about that at all, it's just that's the only place I've seen it), and some other sites where they're all in kanji and I can't read them, though they look like they may be copies of the RD issue page.

Does anyone else know what this thing does, and if (some) of these should be cleared out?

```diff
--                    WebImagePaddingLeft =9
--                    WebImagePaddingTop =8
--                    WebImagePaddingRight =10
--                    WebImagePaddingBottom =13
++                    WebImagePaddingLeft =8
++                    WebImagePaddingTop =7
++                    WebImagePaddingRight =8
++                    WebImagePaddingBottom =10
```

**Comment by joyfullservice** [comment]
Yes, I have encountered similar issues with these values drifting. I did some testing this morning, and these values seem to be reset when importing a form, regardless of what the values are in the source. You can set them from 2 and 1 to 2000 and 1000, but on the next export, they will be reset to 2 and 1 again. If you remove (sanitize) the values entirely, they show up the next time you export.

Based on the fact that these values drift and cause noise in the build cycle, and the fact that the values in the source do not seem to have any effect on the actual objects during build, I vote that we sanitize them from the source files at the standard sanitize level.

**Comment by joyfullservice** [comment]
I am pretty confident that we can just sanitize these values. I went ahead and added this rule and bumped the build version. We can always revert this if we encounter a problem down the road, but the fact that Access recreates these mysterious values automatically makes me pretty confident that we don't need them in the source files.

**Comment by hecon5** [comment]
Closing
