### ISSUE TITLE
UX BUG: When installing V4 latest to new location, UX doesn't tell user how to uninstall

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-addin#427]
When installing V4 post new folder installation, if the default MSAccessVCS folder or Addin accda file exists, the UI states "must uninstall first" even if the old version was uninstalled. If for some reason uninstalling doesn't remove the folder or db files, the error is very cryptic and there's no mechanism to "uninstall". 

Once you navigate to the MSAccessVCS folder and delete it / the contents, then the install continues.

It would be nice to double check during uninstall the files are removed, if that's what "uninstalled" means, and to provide a mechanism to clear those out during the new install; this will be clearer for the user. 

If uninstalling must happen first, then reloading VCS Addin installer, that'd be ok, too.

**Comment by joyfullservice** [comment]
At some point we can probably update this to use the worker script to clear out the files during uninstall, since the worker can run out-of-process and remove itself when finished.

**Comment by hecon5** [comment]
Sounds good; for now, I'll just close this, since it solves the bug :)
