### ISSUE TITLE
Overflow error when I export the source code

### ISSUE THREAD

**Issue by dlangenafa** [joyfullservice/msaccess-vcs-addin#431]
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/143452637/72c0c0a0-661c-4722-993a-10622ac2a8f1)

If I change Dim intCnt As Integer to Dim intCnt As  Long, it works.

**Comment by joyfullservice** [comment]
Thanks for reporting this! You are right, it would be better to declare this as a long since the file size is unknown.

**Comment by hecon5** [comment]
@joyfullservice : as a general practice, unless there are compelling reasons to stick with `integer` (time structures, weirdly), we now require all `Long` variables now for this exact reason.

**Comment by joyfullservice** [comment]
I have corrected this in the source code, so it should roll out in the next beta release.
