### ISSUE TITLE
SqlFormatter chokes on literal Access-formatted dates (e.g., #1/1/2000#)

### ISSUE THREAD

**Issue by mwolfe02** [joyfullservice/msaccess-vcs-addin#440]
The sample code below raises a "Subscript out of range" error:

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/305213/441596b6-a257-43fc-b229-05d28d679772)

```vba
Sub ReproduceSqlFormatterBug()
    With New clsSqlFormatter
        Debug.Print .FormatSQL("SELECT (#1/1/2000#) AS SampleDate")
    End With
End Sub

```

**Comment by mwolfe02** [comment]
I'm guessing the problem is in the `Tokenize` procedure.  Here are the tokens the sample SQL generates:

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/305213/89060a1b-6563-4b55-9524-68da0e93b79d)

This token in particular looks wrong:

```vba
"#1/1/2000#) AS SampleDate"
```

**Comment by mwolfe02** [comment]
Looks like it is treating the opening pound sign (`#`) as the start of a single-line comment:

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/305213/56acfa1a-d78e-4afd-9577-8893222ef4fd)

**Comment by mwolfe02** [comment]
Without the parentheses, we avoid the "Subscript out of range" runtime error, but we still end up with a logic error in that the SQL string is not being tokenized correctly:

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/305213/f89fa7e1-8696-44fb-a8c8-d4f0cee44d6e)

The third token in the screenshot above should actually be 4 separate tokens, as shown below if we replace the date with a numeric literal:

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/305213/c5b3d48e-4f7d-456f-9a57-c9d060705cf0)

**Comment by mwolfe02** [comment]
The following code changes appear to fix the issue, but I haven't tested widely to make sure I didn't break something else:

In the **Tokenize** procedure (replace "Single line comment" code block with this):
```vba
        ' Single line comment
        ElseIf NextChar("#") Or NextChar("--") Then
            Dim TokenText As String
            TokenText = GetTill("#", blnIncludeStopChars:=True)
            If LenB(TokenText) = 0 Then TokenText = GetTill(vbCrLf, vbLf)
            AddToken ttComment, TokenText
```

In the **GetTill** procedure (fix off-by-one error):

BEFORE:

```vba
    ' See if the searched string exists
    lngPos = InStr(m_lngPos, m_strSql, strStopAt)
```

AFTER:

```vba
    ' See if the searched string exists
    lngPos = InStr(m_lngPos + 1, m_strSql, strStopAt)
```

**Comment by joyfullservice** [comment]
Thanks for reporting this! My initial hunch is that this is because Access uses `#` not as a comment character, but as a type of quote or boundary for literal dates. Let me do some testing from that angle, and see if that might solve this...

**Comment by mwolfe02** [comment]
That certainly appears to be what's going on.  The code changes I proposed fix the issue I was having, but I don't know whether they will break other functionality (in particular, dialects where `#` _is_ used as a comment character).

**Comment by mwolfe02** [comment]
Building a perfect parser may be too big a performance hit for this feature.  I think speed, avoidance of bugs, and consistency of output are more important than making sure each bit of text is properly tokenized.

**Comment by joyfullservice** [comment]
I have an initial fix that seems to be working very well, but we would lose support for the MySQL single-line comment in favor of the Access date literal. This isn't a huge deal, but I would feel better about a slightly more robust approach. Working on that now...

**Comment by joyfullservice** [comment]
I just pushed an update that will allow us to support Access date literals _AND_ the MySQL inline comments without needing to provide a dialect hint. Added a test case to demonstrate this. Let me know how this works for you!

**Comment by mwolfe02** [comment]
Looks good, Adam.  I'll test it to be sure and report back.

**Comment by joyfullservice** [comment]
@mwolfe02 - Just circling back to confirm that this issue has been resolved...

**Comment by mwolfe02** [comment]
Yes, it has.  Tested and working. Thanks for the fix.  By the time I got around to testing it, I had forgotten to come back and close the issue.

**Comment by joyfullservice** [comment]
Awesome! Thanks, Mike!
