### ISSUE TITLE
Exporting my project, and immediately exporting it again causes VBA runtime error #5 Invalid Procedure Call or Argument

### ISSUE THREAD

**Issue by NfaToys** [joyfullservice/msaccess-vcs-addin#444]
I'm running Windows 11 on a Dell XPS laptop and Access 2021.   I have the VCS Add-In v3.4.23.

![Screenshot 2023-09-28 143040](https://github.com/joyfullservice/msaccess-vcs-addin/assets/145808213/093d7f45-0d05-4e5c-b3ac-6515a50369a5)
![Screenshot 2023-09-28 142916](https://github.com/joyfullservice/msaccess-vcs-addin/assets/145808213/9690707e-5989-4622-8d11-c7b4e52b9564)
![Screenshot 2023-09-28 142950](https://github.com/joyfullservice/msaccess-vcs-addin/assets/145808213/32b38c66-f2df-4a51-acdd-70f52cc5cd16)
![Screenshot 2023-09-29 164736](https://github.com/joyfullservice/msaccess-vcs-addin/assets/145808213/e8f7cad9-65c1-4b1a-976a-ffeffca3431a)

**Comment by joyfullservice** [comment]
Hi Gary, could you try using the latest beta release? I am pretty sure this issue has been resolved in version 4, and there are a lot of other advantages you will probably appreciate in the newer version. Let me know how it goes!

**Comment by NfaToys** [comment]
I just deleted my previous released version of VCS, downloaded and installed the latest Beta v4.0.21, ran it several times, and I could no longer duplicate the runtime error.   I agree, the problem seems to have been fixed.
