### ISSUE TITLE
Cannot parse SQL with an IN clause

### ISSUE THREAD

**Issue by bclothier** [joyfullservice/msaccess-vcs-addin#447]
Just FYI, this won't parse with the formatter:

```
SELECT foo.* INTO (C:\path\to\bar.accdb) fizz
FROM bazz;
```

It get hung up on the `:` token. In previous version, it was also causing endless loops (#442), but with the current version, we get an error that the SQL could not be parsed. I think the formatter need to be able to handle the variant of `IN` clause, however rare they are, since this is legal Access SQL.

**Comment by joyfullservice** [comment]
Interesting... I have not seen this syntax before. Is Access using the parentheses to "quote" the path?

We absolutely want to support any legal Access syntax, but using parentheses as quotes could be an interesting puzzle for the formatter class...  🤔 Definitely sounds like a case for the dialect hint.

**Comment by bclothier** [comment]
It looks like a variant of the Access SQL's `INTO` but only for make-table queries. Normally, we have this:

```
SELECT foo.* INTO foo IN 'C:\path\to\bar.accdb'
FROM bar;
```

The only way to get this weird syntax is by setting the property as shown:

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/2367644/71d4a554-f493-4c55-ae41-2403cfb84035)

Typically it's the `Destination DB` that is populated but as seen above, `Dest Connect Str` can accept a filepath and it's apparently legal.

In which case we get the parentheses-quoted syntax. I don't think it's legal anywhere else. This gives an error:

```
SELECT foo.* FROM (C:\path\to\foo.accdb) foo;
```

We normally would use this:
```
SELECT foo.* FROM [C:\path\to\foo.accdb].foo;
```

That said, I am very suspicious this is a case where the syntax isn't actually valid but query does work. See, if you do it graphically, it works. But if you copy the SQL and paste it into another query using SQL view, then try to execute it, you get an error about invalid reserved word, highlighting the parenthesis. 

This is a horrid syntax and I'd be solidly in favor of having the SQL Formatter return:

```
SELECT foo.* INTO [C:\path\to\bar.accdb].fizz
FROM bazz;
```

and award the user with a 10K jolt of volt through the keyboard for abusing the query like so. :D

**Comment by hecon5** [comment]
>  user with a 10K jolt of volt through the keyboard for abusing the query like so. :D

HAH!

**Comment by joyfullservice** [comment]
> 
> and award the user with a 10K jolt of volt through the keyboard for abusing the query like so. :D

```vba
#If HAS_STUDENT_KBD Then
    Private Declare PtrSafe Function ZapUser Lib "keyboard_trainer.dll" ( _
        ByRef lpVolts As LongPtr) As Boolean
#End If
```
I wasn't able to test this on my system, lacking the specialized keyboard...   🤔

**Comment by bclothier** [comment]
Wait, this isn't a standard feature on all keyboards?

Suddenly, it all becomes clear....

**Comment by hecon5** [comment]
potentially related to #184

**Comment by joyfullservice** [comment]
Well, since we couldn't solve this through the keyboard training approach, I went ahead and adjusted the SQL formatter to treat colons as a non-spaced boundary character in Microsoft Access SQL. (Very similar to #457 in resolution.)

We are now producing the desired output:

```sql
SELECT
  foo.* INTO (C:\path\to\bar.accdb) fizz
FROM
  bazz
```
