### ISSUE TITLE
Module clsVCSIndex - procedure LoadFromFile - Runtime error 13 - datatype mismatch in CallByName

### ISSUE THREAD

**Issue by ollypsilon** [joyfullservice/msaccess-vcs-addin#452]
https://github.com/joyfullservice/msaccess-vcs-addin/blob/a666c9dbe161d00580c517874955222b1f86e142/Version%20Control.accda.src/modules/clsVCSIndex.cls#L86

With latest VCS 4.0.25 from dev branch I get this error, no matter if I try to export all, export just one selected object or click on "Open Add-in".
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/52780811/c9c5deb2-113f-4b72-90f8-8e5555e793fe)

With 4.0.9 all was fine, see attached export.log.
[Export.log](https://github.com/joyfullservice/msaccess-vcs-addin/files/13318208/Export.log)

**Comment by ollypsilon** [comment]
Looks like this is caused by some config files.
I've renamed the existing .JSON files in source folder and then it was ok.
Wonder which file or setting caused it in detail.

**Comment by hecon5** [comment]
I think another way to deal with it is to use ISO8601 export type, and then it's a non issue. See also #354 as I'm pretty sure it's the same issue.

**Comment by ollypsilon** [comment]
Thanks, going to check on Monday

**Comment by joyfullservice** [comment]
The simple fix is to delete the index file and run an export to regenerate it. (This will update all the dates to your current local format.)

I have spent some time pondering @hecon5's proposed suggestion of using UTC/ISO 8601 for storing dates, and I will respond to that discussion in #354.

**Comment by hecon5** [comment]
This should be fixed on the latest `dev` now; you'll need do an export and the dates should reset. Also deleting the existing index file may help this. Since there's nothing critical in the index (it's used only for change detection) not having an index will just slow down the first export and act more like a full export.

**Comment by ollypsilon** [comment]
Thanks! Export with new version succeeded!
Well, spotted two other issues, will open separate threads.
