### ISSUE TITLE
Potential Bug when using dates in Access Database Properties

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-addin#459]
In accordance with the law of unintended consequences, I've discovered a side effect of the JSON optimizations. If you use an ISO8601 date as a Database Property, this will be exported correctly in the `dbs-properties.json` export. 

HOWEVER: when this date is then imported, it will be converted to a date prior to being converted and then saved as a string (because as far as I can tell, `Database Properties` are stored as strings, similar to how `TempVars` are stored. When this happens, the date is converted to the local machine's date formatting, and if your `Property Get SomeDBProperty` is expecting an ISO8601 string you'll have a bad time.

To me, I think there are two ways to fix this, one of them is easy and will revert back to the way things "were". The other is hard but won't have other side effects and will be a lot more resilient. For now, I think we should take the easy way out, but thought I'd post this up because others are likely smarter than me.

- Option 1: When importing `DbProperties` turn off the date parsing, then turn it back on again for other modules. This effectively reverts back to the way things were for this module and won't have (other) side effects. There's still a chance it'll cause issues down the road, but the known issue won't be a problem.
- Option 2: When exporting the properties, store additional field data with the value so that we can reliably rebuild the field with the data type and field data that was there. This would require a fair bit of tooling to do so, but in my application we already do this for a click tracking and undo / saving mechanism that sidesteps Access's penchant for breaking things related to nulls and whatnot (that is a whole other discussion, and a project I'm planning to Open Source in the next while).

Unless there are other thoughts, I think the short term answer is to just disable the json date parsing when importing DB Properties; this goes back to the known / expected prior answer, and we can decide longer term what to do.

**Comment by mwolfe02** [comment]
> Option 2: When exporting the properties, store additional field data with the value so that we can reliably rebuild the field with the data type and field data that was there. This would require a fair bit of tooling to do so...

Perhaps my [`CreateDTO()` function](https://nolongerset.com/complex-dtos-in-vba/) could provide the "fair bit of tooling" required to make this second option work.  The CreateDTO() function itself generates a class module with `.Serialize` and `.Deserialize` methods that convert one or more strongly-typed values to and from String values.  I mainly use it as a way to pass strongly-typed values back and forth via OpenArgs, but the same approach could be used with any String-based property, including database properties.

**Comment by hecon5** [comment]
Neat! It's funny, I've not seen that article before, despite having read your blog for a good while. That said, you solved a number of issues I did in similar ways, and we also pass in a multitude of open args via a similar mechanism I based originally off an idea one of your SO comments gave me. That morphed into the ability to track almost any field type change and cache it, detect the type with a very high degree of certainty (we still find an oddball edge case from time to time, mostly around SQL objects like storing a JPG in a field column), but 99.999% of the field types and whatnot are reliably stored via a JSON string.

**Comment by joyfullservice** [comment]
I went ahead and implemented "option 3" where the date value is stored as UTC in the source file, but as a local date in the actual database property. Since we already know from the property `.Type` that this is a _date_ value, I just performed the UTC conversion when _reading_ or _writing_ any `Date` property. This also solves the issue of not inadvertently converting other property types to UTC datetimes just because they could be a date. (For example, if you store a date as a custom property as a `String` type (`dbText`), it will not be converted to an ISO date in the source file.)

**Comment by joyfullservice** [comment]
For reference, I also turned off the UTC/ISO date conversion default since this is actually only used with the Index file, and one subset of one component type. All other JSON content used by VCS should be processed without date conversion. (We don't want to risk corrupting someone's source data by doing unrequested conversions of date values.)

**Comment by hecon5** [comment]
Do we also have an ISO8601 string stored as text? That way we can confirm both correctly import/export regardless of whether they look like a string or not.

**Comment by joyfullservice** [comment]
No, but that's a good idea. Let me add that to the testing database...
