### ISSUE TITLE
GetUncPath - runtime error 76 when UNC path not available

### ISSUE THREAD

**Issue by ollypsilon** [joyfullservice/msaccess-vcs-addin#461]
https://github.com/joyfullservice/msaccess-vcs-addin/blob/3ad141c620b609ba4838dbf18623e8e2c8be502c/Version%20Control.accda.src/modules/modFileAccess.bas#L541

I crossed this error when testing version 4.0.28.
UNC path wasn't available at export as it's a remote system, so the error was raised.
References #385 and tackles #417
As describe there maybe error could be fetched, entry created in log file and user notified.

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/52780811/095ac615-1ca0-4c59-a056-6f566e24be73)

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/52780811/d7f7ba3e-627f-4477-b6f1-84e4a7f070df)

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/52780811/324379fc-410d-4486-ab94-18957b9fc29e)

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/52780811/7edae0e6-193f-48ef-b745-fa3b90e813e3)

**Comment by joyfullservice** [comment]
Since failing to resolve a mapped drive to a UNC path may not actually prevent the export from completing, I set this to a warning rather than an error. The error condition is now handled, and a warning added to the log file.

**Comment by ollypsilon** [comment]
Thx; I'll close it.
