### ISSUE TITLE
 Does not work in Access 2007

### ISSUE THREAD

**Issue by MichellJauregui** [joyfullservice/msaccess-vcs-addin#464]
Hi,
Your project is **incredible** and **beneficial** for all of us. 
It works perfectly in versions 2010 onwards but in version 2007 it does not work, please help, what could I do to make it work in 2007? Thank you so much

**Comment by hecon5** [comment]
I think your best bet will be to upgrade the file to 2010 stepwise and then export. see also #289 #362 or most especially #432 for some ideas on how to accomplish this.

**Comment by joyfullservice** [comment]
Hi Michell,

Access 2010 is the lowest supported version for this add-in. Here are the main reasons for that:

- Access 2010 is what I use at work and at home, and what I use for developing this add-in.
- 2010 includes VBA 7 with native support for 64-bit. This means we can (in most cases) use the same declarations for API calls without having to use compiler directives (`#If win64 Then`).
- There are a few [object model changes](https://www.fmsinc.com/microsoftaccess/history/features.htm) (such as shared images) that aren't available in Access 2007. 

That being said, this project is open source, and anyone with the interest could fork the project and adapt it to work in Access 2007. It's not something that I personally have the time or interest for, but I am sure there are people out there that would probably use it if it was available.

Here's what that would probably look like:

- Fork the current project. (I would definitely go with version 4, currently in the `dev` branch, but probably moving to `main` in the next few weeks or months.)
- Add compiler directives for API calls that use unsupported datatypes like `LongLong`.
- Define an application constant, and use compiler directives to ignore the code sections that involve object model items that don't exist in Access 2007.
- Work through any remaining compile issues. (That sounds easy, right!)
- Test export and build functionality.

The ribbon will _probably?_ work in Access 2007, but I have not done any testing with that version.

Hope that helps!

**Comment by hecon5** [comment]
@joyfullservice we should probably update the wiki to state 2007 isn't supported, I'm thinking [Supported-Objects](../wiki/Supported-Objects) might be a good home for that info.

**Comment by hecon5** [comment]
@MichellJauregui can we close this issue with the outcome at hand?

**Comment by MichellJauregui** [comment]
Hi, I built a file compatible with access 2007 and moved the tables and logic, I didn't manage to run the script, but I updated some of the initial code to make the compatibility work. I have already started the path, I leave you the link so you can take a look. Thank you so much

https://github.com/MichellJauregui/msaccess-vcs-addin/tree/MJV_VERS_OLD/Vers.2007

**Comment by MichellJauregui** [comment]
> @MichellJauregui¿Podemos cerrar este tema con el resultado que tenemos a la mano?

I sent them a comment, progress may be made. Thank you so much

**Comment by hecon5** [comment]
@MichellJauregui FYI: I think you forked the `main` branch instead of the `dev` branch.

**Comment by hecon5** [comment]
@joyfullservice : I think this could probably be closed when `dev` wiki is published to the [Wiki](../wiki)
