### ISSUE TITLE
Feature: Version Check on Active Project

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-addin#465]
I realized some of our devs are not all using the same VCS when a bunch of previously sanitized info got committed. Normally, that's not a problem when we're careful, but we've got a new member who is still getting the hang of our particular workflow. 

To that end: it might be good to verify the VCS Addin version in use versus the version number listed in `vcs-options.json` under `AddinVersion`.

Thoughts on operation when version in `vcs-options.json` is:
- Higher than installed (in use) version: alert user and preferentially bail out so user can update VCS. Maybe even load the website to download latest version, though this will annoy teams where they're using a version off `dev`.
- Same as installed (in use) version: continue on merry way.
- Lower than installed (in use) version: let user know they should update `vcs-options.json` and to let other devs know, too.

Once the Addin has checked in a session, I think it'd be best if the answer was cached until the next session (eg, Access is closed/reopened or VCS is reloaded). This will reduce annoyoprompts which will almost certainly get ignored and train users to ignore prompts. Alternately, we could put the "last time we checked the version" in `vcs-index.json` on export since that never gets committed to git (normally...), and just check once every hour or two?

Should probably also consider a setting in options to determine if this is active or not, and default to on.

**Comment by joyfullservice** [comment]
I have implemented this on the `dev` branch. If you run an export with a newer VCS version, it will notify you that VCS has been updated.

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/7254992/6a3828fa-a19a-4929-b0c7-38f7404dcfbb)

If you begin an export with an older VCS version than was last used, a warning will be shown, and the user will have the option to cancel the export.

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/7254992/a9e92906-6bfc-48fd-b293-ee70618f1c89)

**Comment by joyfullservice** [comment]
I suppose it would probably be a good idea to have a similar check on build... You could get unexpected results if you build a newer set of source files than what the add-in was expecting. 🤔

**Comment by hecon5** [comment]
> unexpected results

I'm not sure if that's accurate or not, but these two pictures are the same, yah?

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/54177882/f098d6d4-bcf1-4dd3-8e30-fb97e50d4105)

**Comment by joyfullservice** [comment]
I guess it's a good thing I am not trying to build images from source...  🤔

**Comment by joyfullservice** [comment]
Okay, this should be set now. It checks on export and build, and warns if you are trying to use an older version than the project was last saved with.
