### ISSUE TITLE
VCS 4.0.21: Error building back end database Data Type Conversion Error Importing dbs-properties

### ISSUE THREAD

**Issue by arpm-awv** [joyfullservice/msaccess-vcs-addin#466]
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/93222092/5a8c2c8c-9e91-4525-a0f1-71b5f091e32b)

Error appears to be occurring in `IDbComponent_Import()`

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/93222092/351d15f1-7042-4ea1-bd0a-810cc188e4e6)

I think the offending item in dbs-properties.json is:

`"LatestLogTimestamp": {
   "Value": "2023-10-27T16:41:12.000Z",
   "Type": 8
 },
`

looking at the value of the variables: 

`varKey = "LatestLogTimestamp"`
`varValue = "2023-10-27T16:41:12.000Z"`
`dItems(varKey)("Type") = 8`

EDIT: Using Build AS... from the Ribbon

Building  the DB the way I did with VCS 3.x completes, but shows the error in the log:
`ERROR: Build error in: C:\Users\awv\Documents\rs\General and Prof_be.accdb.src\dbs-properties.json
Error 3421: Data type conversion error. Source: modImportExport.Build`

Along with a few other errors from linked tables where the source was in the same folder and the build is done in a different folder from the original (I believe you are aware this).

**Comment by hecon5** [comment]
What version of VCS do you have? This looks suspiciously like the issue in #459 which was solved by dealing with the properties explicitly.

**Comment by arpm-awv** [comment]
VCS 4.0.21

**Comment by hecon5** [comment]
If you update to the latest beta (currently v4.0.28) from `dev`. This was fixed in adfaa0110e11936146e93b813ac711db3eae69c9 and b32ff4a31d16c84e4d7b1e804d707340ce05734e (where the values are tested to make sure the dates can go through a loop).

**Comment by hecon5** [comment]
> VCS 4.0.21 

@arpm-awv ...if only there was a title, or something that said that... whoops! 🥇

**Comment by hecon5** [comment]
Did this get resolved when you built with the latest version?

**Comment by arpm-awv** [comment]
> Did this get resolved when you built with the latest version?

No, see #467.

**Comment by hecon5** [comment]
Ok, if that's the same issue, please close one of them as it's harder to track duplicates. If the data type conversion issue is fixed, close this one and we can focus on the other (different) issue to fix.

**Comment by arpm-awv** [comment]
I wouldn't call it the same issue. I was told it was fixed in a later version but was unable to use the later version for a different reason.
