### ISSUE TITLE
Bug: Merge Build Still tries to re-connect/rebuild linked tables

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-addin#472]
One thing I was hoping merge-build would do is to not reconnect/rebuild linked tables, as that's the slowest step there is for me. I'm not sure how/why this is, but it seems that the linked tables seem to always be relinked on merge build, which takes eons for me.

**Comment by joyfullservice** [comment]
Right, it should not be relinking an existing table when nothing has changed on the link side... I haven't (yet) noticed this issue myself. Are you linking to tables in a SQL database?

**Comment by hecon5** [comment]
Yes, MS SQL; I'm wondering, does the index check the hash of the tables, or just their existence for linked tables?

**Comment by joyfullservice** [comment]
Reviewing the code, it appears that it is comparing the modified date of the table object to the date saved in the index. If you do a little testing, can you determine when the table modified date changes? It may be that we need to take an alternate approach for linked tables and compare the hash of the link information as a second step if the dates don't match, just to avoid relinking when nothing has actually changed.

**Comment by hecon5** [comment]
That's what I thought was going on, but I couldn't tell. I will investigate on what might force a date change on the table.

**Comment by hecon5** [comment]
So, I did a fresh (full) build from source, and then immediately did a merge build, without changing anything. The tables all seem to be re-imported, so either the date saved is whatever time the system checks (eg, is never not `now`), or the index is comparing an unknown value.

Since I haven't dug into that specifically, when merging, does the merge logic check the `ImportDate` and `SourceModified`? It looks like `ImportDate` is actually before `SourceModified`, which maybe is causing the conflict? When importing, should `SourceModified` be updated as well?

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/54177882/e8308f44-7ce8-4751-8ab7-5c972538e2f7)

**Comment by hecon5** [comment]
Interestingly, the merge build DOES seem to skip table merging on the second and subsequent merge, so it seems like something is changing, but what I don't know. The hash values stay the same through the merge, too, so I'm flummoxed at the moment.

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/54177882/27246a83-11c0-409e-89c4-7fee3ac3c938)

**Comment by joyfullservice** [comment]
Hmm... I am having trouble reproducing this. I created a test database, linked a couple tables from a Microsoft SQL Server, and ran various exports, builds, merges, rebuilds, etc... but everything works the way I would expect.

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/7254992/238514da-f57a-40c4-81a9-83bb766bf480)

Even a merge immediately after a build does not detect any source changes or force a relinking of the tables. As I think about it, change detection during a merge is looking for changes in your source files when compared to the index. The change in the source files for `tabledef` objects is determined by the source file date. Are the modified dates changing in your source files?

It might be easiest to troubleshoot if you create a sample database, link a couple tables, then step through the code if you are still encountering issues with the merging...

**Comment by hecon5** [comment]
So, doing some more testing, and it looks like if I close / reopen the DB a day later and export, the table are all re-exported, after a merge build, and export, all the tables get exported, even if they didn't change. When I did a merge build, this time, the tables did not re-import.

This morning, when I did an export>import> merge, the merge didn't export anything, but if I then exported, the export dates (and date of modification) did update for most objects in the database (and the hash, did too). The contents of those changes did not seem to change (git didn't see any edits), so I'm thinking that either the hash isn't consistently being built, there's something modifying the tags in the db, or maybe both. 

I'm going to keep troubleshooting, and will update if I figure anything else out.

**Comment by hecon5** [comment]
Alright: made a happenstance discovery. 

If I build a db from scratch, then export the db, it appears merge build works correctly. I noticed a few forms export differently than what they imported as (case changes that occur as a result of the case of an imported SQL field). So either those tables get reimported, or something about the export corrects the index. There's nothing to indicate the table defs changed (git sees no change) so I think it's tied to something about the index.

**Comment by joyfullservice** [comment]
> I'm wondering, if after a build the index update should be performed

That's a bit of a tricky one... After a build, we can be confident that the source files are current with the build, but it might be a bit dangerous to assume that the database objects would export to identical source files. One approach would be to do an export to a temp folder immediately after a build to ensure that the exported files match the source files. (Maybe this would be an option to "verify after build").

On the merging side, I am in the middle of some significant refactoring to better handle orphaned objects and source that involves more than one file representing an object. I hope to work through these updates this week, which would make the merging process a lot more robust.

**Comment by hecon5** [comment]
Sounds good; I figured it was; the export after build doesn't take long, and once done, the merge build works as expected.

**Comment by joyfullservice** [comment]
I just pushed a bunch of commits to `dev` that I have been working on this week. Change detection and orphaned object treatment should be working much better now, based on my limited testing.

**Comment by joyfullservice** [comment]
Hmm... I am having trouble reproducing this behavior... I have a test database with two linked SQL tables, and I can build from source, and immediately merge build, but no changes are detected.

Do you think something might be changing with the connection string or another property? You could add some break points to review the hashes during the build and scan process... It might be easiest to do this on a test database that only has a couple tables. Let me know what you find out.

**Comment by hecon5** [comment]
The hashes do change, from what I can tell. But they change after build (aka, from one build to another they're different, but within that build they dont' appear to change provided the table isn't changed). The build hash doesn't seem to be updated in the index from what I can tell.

**Comment by hecon5** [comment]
Here's an excerpt from the index on two of the tables. From watching the hash, `FilePropertiesHash` does not get updated until after the first export (or build) after building the database. I've looked and looked, and the export doesn't actually change anything (no changes detected on the export), so either there's a hidden property or something that's sanitized out which is part of the hash value. 

This happens whether it's one table or 150. 

```JSON
        "dbo_qryFrmViewLCs.json": {
          "ExportDate": "2023-12-13T20:56:47.000Z",
          "SourceModified": null,
          "FilePropertiesHash": "180adfe",
          "ImportDate": "2024-01-03T15:36:56.000Z"
        },
        "dbo_qryFrmViewLCs.xml": {
          "ImportDate": "2024-01-03T15:28:01.000Z",
          "SourceModified": null,
          "FilePropertiesHash": "180adfe"
        }
```


From `clsDbTableDef`, it almost looks like `IsModified` should always return true after a build, because the internal date should be Now minus some seconds, whereas the export date may be months ago, and the hash value is based on the prior value; where as once you export, the hash is updated in the index, and is now valid.

```VBA
'---------------------------------------------------------------------------------------
' Procedure : IsModified
' Author    : Adam Waller
' Date      : 11/21/2020
' Purpose   : Returns true if the object in the database has been modified since
'           : the last export of the object.
'---------------------------------------------------------------------------------------
'
Public Function IDbComponent_IsModified() As Boolean
    IDbComponent_IsModified = (m_Table.DateModified > VCSIndex.Item(Me).ExportDate)
End Function


'---------------------------------------------------------------------------------------
' Procedure : DateModified
' Author    : Adam Waller
' Date      : 4/23/2020
' Purpose   : The date/time the object was modified. (If possible to retrieve)
'           : If the modified date cannot be determined (such as application
'           : properties) then this function will return 0.
'---------------------------------------------------------------------------------------
'
Private Function IDbComponent_DateModified() As Date
    If m_Table Is Nothing Then Exit Function
    IDbComponent_DateModified = m_Table.DateModified
End Function

```

**Comment by joyfullservice** [comment]
Thanks! That is helpful. I think the underlying issue here is that we need to go ahead and set the hash value after importing the object from source. `TableDef` is one of just a few objects that were not setting the hash value during import, but this is easy enough to correct. Working on some updates now...

**Comment by joyfullservice** [comment]
Let me know how it works after a fresh build from `dev`.

**Comment by hecon5** [comment]
Will do; probably be tomorrow before I can get to this, thanks!

**Comment by hecon5** [comment]
This fixed it! Thanks!

**Comment by hecon5** [comment]
Picture of success :) 
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/54177882/c98f5d3c-b0ac-4d96-9e13-3b7b7292ea08)
