### ISSUE TITLE
Unexpected Changes in Form and Report Properties after Build and Export

### ISSUE THREAD

**Issue by Festiis** [joyfullservice/msaccess-vcs-addin#479]
### Steps to Reproduce:
1. Build from source on a laptop or a different screen rezolution from the one that exported source.
2. Export all source right after the build.

### Expected Behavior:
Expected the exported source to be the same as the imported, since no changes was made.

### Actual Behavior:
Upon exporting the source, MS Access made unexpected changes to various form and report properties. For example:
- On Form "A" the FormHeader Height property changed
  Height =334  ==> Height =342  
- Form "A" Label "lblTitle" Left property changed
  Left =3255 ==> Left =3248
- Label "lblTitle" LayoutCachedLeft changed
  LayoutCachedLeft=3255 ==> LayoutCachedLeft=3248
- Label "lblTitle" LayoutCachedWidth changed
  LayoutCachedWidth =8250 ==> LayoutCachedWidth =8243
- All forms containing Buttons, properties WebImagePaddingLeft, WebImagePaddingTop, WebImagePaddingRight,  WebImagePaddingBottom changed
- Reports PageFooter property Locked has been added to some of the reports and removed from some other reports.

The result is that git says 257 changes has been made.

### Version Information:
```
"Info": {
    "AddinVersion": "3.4.23",
    "AccessVersion": "16.0 64-bit"
  }
```

### Reproducibility:
I can reproduce it on any laptop or pc.

**Note:** Please let me know if any additional information is required to address this issue. 
I am aware that this may not have anything to do with the add-in, but I'm hoping someone may have found a workaround.

**Comment by bclothier** [comment]
This may help:

https://github.com/joyfullservice/msaccess-vcs-addin/wiki/FAQs#why-am-i-seeing-a-large-number-of-changed-files-after-building-my-project-from-source

**Comment by Festiis** [comment]
Thank you Sir

**Comment by joyfullservice** [comment]
@Festiis - One other tip to pass along... You might want to try the beta version as well. It is pretty close to general release, and has many improvements over version 3.

**Comment by Festiis** [comment]
Thanks a lot, i will grab it right away!
