### ISSUE TITLE
How can hide the version control in the ribbon 

### ISSUE THREAD

**Issue by sotalvaro** [joyfullservice/msaccess-vcs-addin#480]
Hi Adam, I need hide the version control options in the ribbon,
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/138826677/c17021ee-9f1b-455e-899c-2936306e4bcf)
I used this command line,
Call DoCmd.ShowToolbar("Ribbon", acToolbarNo, "Version Control")
but I found this error,
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/138826677/827c09c5-ae80-495f-9e96-cf8db1da7c4e)

Thanks man!!

**Comment by joyfullservice** [comment]
@sotalvaro - I think that command is to show or hide the entire ribbon, not just a single tab. You can use VBA to unload the COM add-in, and that will remove the Version Control tab.

`ComAddIns("MSAccessVCSLib.AddInRibbon").Connect=False`
