### ISSUE TITLE
Bug: Error 3283 Primary key already exists

### ISSUE THREAD

**Issue by Dlothcab** [joyfullservice/msaccess-vcs-addin#484]
Started having issues just yesterday when building from source.  I am getting an error messages in the build log for every linked SQL Server table. The linked views do not cause an error.

From Log:
  ERROR: Unhandled error, likely before `On Error` directive
  Error 3283: Primary key already exists. Source: .Unknown.LogUnhandledErrors

I had version v3.4.23 installed and would get an overflow message and the build would stop. I just updated to the latest beta version this morning. I am still getting the error messages in the log for every table, but the build completes and the tables relink.

**Comment by joyfullservice** [comment]
Thanks for reporting this! Can you try checking the option to debug VBA Errors, and let me know where the error occurs? It might help us see exactly which line is failing, which could give us some further clues...

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/7254992/34b50000-9ef9-4c8d-b263-82454e7e741d)

Also make sure you have done a full export from the version you are trying to build with. (I assume you probably did, but just in case. 😄)

**Comment by Dlothcab** [comment]
I had not done a full export after updating to the beta version.  I'm still getting the error messages on build after the full export.

Working backwards on the call stack:
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/104448478/12547a34-7f57-4fc3-9919-28efd5390177)
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/104448478/d8f716c5-2d88-4987-abe3-52cc3a85f277)
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/104448478/9460e098-d5e5-4f13-b782-76aed06d96eb)
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/104448478/e5221b77-a403-46b2-a057-100121a55203)
The last image is from the ImportLinkedTable function
dItem.Exists("PrimaryKey") is true

**Comment by joyfullservice** [comment]
Thanks for the screen shots! That is very helpful. It seems that the issue is related to attempting to create an (unneeded or duplicate?) primary index on the linked table. (Or linked view.)

`LogUnhandledErrors` reports any previous errors that were not already handled before they are cleared by a new `On Error` directive, so the actual source of the error is probably actually in a previous operation.

Is this on a specific SQL table or view that you are linking to? If so, would you be able to post some details on the composition of the index, and how this is reflected in the exported source file? (You don't need to post any sensitive connection information, but the index details may be helpful in pinpointing the problem.) You mentioned that the error is logged for every linked table, so perhaps there is something similar with all of them. (Perhaps composite keys, or something like that?)

I am pretty confident we should be able to resolve this, it is just a matter of pinpointing exactly where the error is thrown, and determining how to handle the situation. I have access to a SQL server, so I may be able to replicate the issue if I have enough details, or perhaps a SQL script to build a sample table.

**Comment by Dlothcab** [comment]
It is every table but not any of the views.

Here is an excerpt from the build log. The first two tables are local Access tables.
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/104448478/b1a2ff41-4959-47ab-bcae-65724cc50dff)
Another excerpt, table names with a "v" are views
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/104448478/7273013b-9b30-4489-a36e-c2969bdaa9ea)

Here is the json file for the first table (connect string is cleared out)
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/104448478/852eed7a-f7b8-4ccd-aa11-d59015d94fa7)
Here is the sql file for the same table
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/104448478/0670f232-1cd6-4177-a338-d899386df331)

**Comment by Dlothcab** [comment]
I have a primary key added to some of my views, but these don't have an error.
example: AP_vContract_Detail
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/104448478/20e1eaed-bdc2-4917-989e-86c684d37790)
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/104448478/675f4a0e-383a-4d81-91a1-ad3fa6939ff8)

**Comment by joyfullservice** [comment]
Thanks! On the SQL server side, would it be easy to generate a build script for the table? That would have any additional attribute/index details that might be pertinent here... (That would allow me to use the same script to generate an identical table on my SQL server to see if I can reproduce the issue.)

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/7254992/60a1b8c6-4eb2-4d0d-848d-3bb3e8746900)

**Comment by bclothier** [comment]
FWIW, because as noted earlier, the error is likely from previous operation, I wonder if the problem may be with the attributes. I'm aware that when creating a new `DAO.TableDef`, not all attributes can be set.

**Comment by Dlothcab** [comment]
[AP_Contract create.txt](https://github.com/joyfullservice/msaccess-vcs-addin/files/13992522/AP_Contract.create.txt)
[Inventory_Formula create.txt](https://github.com/joyfullservice/msaccess-vcs-addin/files/13992523/Inventory_Formula.create.txt)

**Comment by Dlothcab** [comment]
I don't know if this is helpful at all, but I ran these in the immediatewindow from the ImportLinkedTable function
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/104448478/5358dfcc-8189-40de-9b60-29950260be54)

**Comment by Dlothcab** [comment]
I uncommented the On Error Resume Next line in ImportLinkedTable and stepped through each line, checking the err.number in the immediate window.  The error shows up after running tdf.RefreshLink.
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/104448478/34625a11-8e9f-4eba-b994-1965658c84c1)

**Comment by joyfullservice** [comment]
Could this possibly be an issue with a recent Access update (bug)? https://learn.microsoft.com/en-us/answers/questions/1486159/when-i-run-refreshlink-i-get-an-error-saying-prima

**Comment by joyfullservice** [comment]
I used the SQL script (with a few modifications) to add one of the tables to a SQL server, but I could not reproduce the issue in Access 2010. (The export and build worked as expected.) That does make me curious to know if this a bug in a new release... In any case, I will add some error handling around the linking.

**Comment by Dlothcab** [comment]
This is my version: Microsoft® Access® for Microsoft 365 MSO (Version 2401 Build 16.0.17231.20084) 64-bit

**Comment by joyfullservice** [comment]
Do you get any error if you refresh the link using the linked table manager? (In theory, that would be the same thing that we are doing when we call `.RefreshLink` on the linked table.)

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/7254992/278c61a1-6595-4945-843f-8b8ac5988cdf)

Just trying to think of ways to drill down into the issue...

**Comment by Dlothcab** [comment]
No, I do not get any errors when refreshing the links via the linked table manager.

**Comment by joyfullservice** [comment]
So, walking through this process, we are creating a new tblDef object, setting the connection string and some attributes, then appending it to tblDefs collection. (Adding it to the database) 

```vba
    ' Read json file
    Set dTable = ReadJsonFile(strFile)
    If Not dTable Is Nothing Then

        ' Link the table
        Set dItem = dTable("Items")
        Set dbs = CurrentDb
        Set tdf = dbs.CreateTableDef(dItem("Name"))
        strConnect = GetFullConnect(dItem("Connect"))
        With tdf
            .Connect = strConnect
            .SourceTableName = dItem("SourceTableName")
            .Attributes = SafeAttributes(dItem("Attributes"))
        End With
        dbs.TableDefs.Append tdf
```

After adding it to the database, we are then verifying that the connection string hasn't changed from what we used when creating the table. (See #192)

```vba
            ' Verify that the connection matches the source file. (Issue #192)
            If tdf.Connect <> strConnect Then
                tdf.Connect = strConnect
                tdf.RefreshLink
            End If
            dbs.TableDefs.Refresh
```
In this case, the connection string _has_ changed, so it is being set again to the value read in the source file. It is at that point that you hit the error refreshing the link. (Updating the connection using the applied connection string.)

Perhaps you could do a little testing to compare the actual connection string after appending the tabledef to the one we are attempting to set, and even try manually setting the connection string and refreshing the link to see if we can isolate the error to perhaps something in the connection string...

`CurrentDb.TableDefs("AP_Contract").Connect="my test connection string"`

**Comment by Dlothcab** [comment]
I am using a trusted connection.  The difference between the connect string stored in the variable strConnect and the .connect property of the table after it is appended is the UID field.  
tdf.connect has UID=
strConnect does not have UID=

**Comment by joyfullservice** [comment]
Okay, it doesn't seem like that should make a difference... 🤔 Do you get any errors when setting the connection string and refreshing the link manually through VBA in the immediate window?

**Comment by Dlothcab** [comment]
Yes, running Currentdb("AP_Connect").RefreshLink causes error 3283

**Comment by joyfullservice** [comment]
What if you link that table manually in another test database, then try the `RefreshLink` command in the immediate window. Just trying to narrow down the issue here...

Another thing that might be worth trying is running a SQL Server Profile trace against the SQL server while triggering the error. Sometimes there are additional messages or clues that I can pick up that way.

**Comment by Dlothcab** [comment]
I created a new database and manually linked the table. Refreshing the link in the Linked Table Manager works without error, but running CurrentDb("AP_Contract").RefreshLink in the immediate window causes error 3283.

I've never done a SQL Server Profile trace before.  There is a lot going on in 0.15 seconds!  I found the log where I am the one connected, but can't make sense of any of it.
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/104448478/b042f817-851d-4036-814a-a58919b8e6ce)

**Comment by joyfullservice** [comment]
Very interesting. The SQL trace looks pretty similar to what I am seeing on my server. I am still rather perplexed as to why we get an error when using the `.RefreshLink` method... Obviously we could just ignore it and go on, but I have a nagging interest in knowing why it is coming up in the first place.

I have never encountered this before on my systems, and can't seem to reproduce it, so I am not sure how to troubleshoot this going forward...  🤔

**Comment by bclothier** [comment]
FWIW: I have found that it's usually more reliable to delete & re-create a tabledef than executing `RefreshLink`....

**Comment by joyfullservice** [comment]
> FWIW: I have found that it's usually more reliable to delete & re-create a tabledef than executing `RefreshLink`....

Reviewing the logic flow here, the tabledef has already been created from scratch. This was just a second check to make sure the resulting connection string still matches what we gave it when creating the linked table. (Most of the time this isn't an issue, but it can sometimes lead to unexpected results in rare situations. See #192)

If the connection string doesn't match, and we attempt to reset it and refresh the link and it still throws an error, my hunch is that we can probably just proceed with the build and not worry about it. It should be a very rare scenario with several specific factors for this to occur, so I don't know that it is a big enough issue to warrant anything beyond adding the note to the log file.
