### ISSUE TITLE
The database engine could not lock table 'tblTableData' because it is already in use by another person or process.

### ISSUE THREAD

**Issue by imjosh** [joyfullservice/msaccess-vcs-addin#491]
msaccess-vcs-addin v4.0.34
Microsoft Windows [Version 10.0.19045.3930]
MS Access 2016
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/3116028/330874c8-dee8-4d4a-82b4-e5c17627d4b7)

After just installing the add-in, when I choose "View Options" I get the following error message:

The database engine could not lock table 'tblTableData' because it is already in use by another person or process.

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/3116028/02133cd9-63c5-4fb0-9a03-5f4ea37e2fb5)

thanks

**Comment by joyfullservice** [comment]
Hi Josh, that seems kind of strange... If you completely close all instances of Microsoft Access, then try again, do you still get the error? If so, I would try reinstalling the add-in. Let me know if you are still having the issue.

**Comment by hecon5** [comment]
Did you trust the addin when you loaded it? This sounds exactly like an issue we had when the Addin wasn't trusted properly (or opened after install).

**Comment by imjosh** [comment]
Reinstalling the add-in resolved the issue, thanks
