### ISSUE TITLE
Error when click on View Options

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [joyfullservice/msaccess-vcs-addin#499]
When I click in View Options button, I get this error:
```
dbs.Execute "DELETE FROM tblTableData;", dbFailOnError
```

**Comment by joyfullservice** [comment]
Try closing all instances of Microsoft Access, and reinstalling the add-in. Let me know if that fixes it.

**Comment by pmoreno-rodriguez** [comment]
@joyfullservice , it works fine now. Thanks
