### ISSUE TITLE
VSCode gets not recognized when system installer was used

### ISSUE THREAD

**Issue by noethneuberger** [joyfullservice/msaccess-vcs-addin#502]
If VSCode was installed with the system installer the exe is under C:\Program Files\Microsoft VS Code.
The clsViewDiff module in Line 211 only checks the for the user installer.
Is it possible to add a check for the system installer, too?

**Comment by hecon5** [comment]
I made a Pr for this. Should be incoming in a moment.

**Comment by noethneuberger** [comment]
Thank you

**Comment by joyfullservice** [comment]
Thank you both! Great suggestions. 👍
