### ISSUE TITLE
Export/import "Conditional Compilation Arguments"

### ISSUE THREAD

**Issue by mwolfe02** [joyfullservice/msaccess-vcs-addin#511]
This request was raised during my presentation on the Add-in at DevCon Vienna 2024:

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/305213/06b59341-a8e1-4148-a4cd-f0299e4a4c99)

Should be as simple as incorporating the following code:

```
Application.SetOption "Conditional Compilation Arguments", "Test=1"

?Application.GetOption("Conditional Compilation Arguments")
Test = 1

```

**Comment by joyfullservice** [comment]
Good news! That is already supported. The source can be found in `clsDbVbeProject`.

**Comment by hecon5** [comment]
@mwolfe02 is this working as expected? If so, can you close it?
