### ISSUE TITLE
I can not install the add-in in the Add-in Manager

### ISSUE THREAD

**Issue by thefoz1959** [joyfullservice/msaccess-vcs-addin#512]
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/75589393/83ac07b1-c440-4f38-ac6c-c4e718f6e621)

**Comment by joyfullservice** [comment]
This add-in is not installed through the add-ins manager. It has its own built-in installer that is launched when you open the add-in file. https://github.com/joyfullservice/msaccess-vcs-addin/wiki/Quick-Start

**Comment by thefoz1959** [comment]
Thanks it workend. Do you have tips to use it with github?

Thanks Paul

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by joyfullservice** [comment]
Hi Paul,

I am glad it is working for you! It is designed to work with GitHub right out of the box, and will add the `.gitignore` and `.gitattributes` files for you. You might check out this video from DAAUG where I demonstrate using the add-in in a GitHub project: https://www.youtube.com/watch?v=85sVx6HnpXQ

I will go ahead and close out this issue, but feel free to reach out if you encounter any further issues!

- Adam
