### ISSUE TITLE
Big News! You can now sign Access VBA files!

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-addin#513]
Huge news: (this may be old news to others...)

Apparently in the latest builds you can sign Access VBA environments! 

This makes things quite interesting! 

I don't know if anyone has tried, but it would be REAL cool if the build environment could build a database, sign it (with a stored cert), then deploy. This is a missing piece of trust we've been wanting for a while, this is so cool.

[Microsoft Show trust by adding a digital signature](https://support.microsoft.com/en-us/office/show-trust-by-adding-a-digital-signature-5f4ebff3-360d-4b61-b2f8-ce0dfb53adf6)

**Comment by HughWarrington** [comment]
Yes and there's a great and very thorough guide to it by Colin Riddington here: https://isladogs.co.uk/vba-project-signing.

**Comment by hecon5** [comment]
Closing as this is likely old news and doesn't directly pertain to this addin.
