### ISSUE TITLE
Run-Time error 3110 on first Export

### ISSUE THREAD

**Issue by MwaltmanFEI** [joyfullservice/msaccess-vcs-addin#523]
![image](https://github.com/user-attachments/assets/bd2e561d-dce9-453a-9364-816ebc8bf062)

error on read definitions for unknown table or query.  has anyone else experienced this?  I attempted to turn off fast save option and still receive same error during table export step.  Any help is appreciated!

**Comment by joyfullservice** [comment]
Hmm... I have not seen that before. Which version of Access are you using, and do you have any special permissions/security on the database that would affect the ability to read objects? You might also try a Compact/Repair after making a backup of the database. You could possibly be [encountering some issues](https://answers.microsoft.com/en-us/msoffice/forum/all/access-database-shows-could-not-read-definitions/bc8a5e25-89b3-4822-98a4-c08821a1574b) in the database unrelated to the add-in.

Let us know how it goes!

**Comment by MwaltmanFEI** [comment]
Hi I'm using Version 2406 Build 17726.20160.  I am using mostly SQL linked tables but do have a few Access tables in play as well.  I've tried compact and repair with no change.  The names of the "tables or queries" listed in the error are not familiar and I'm not able to locate them.  Not unusual for Access to provide vague information on the error dialog though :).

**Comment by Tanarri** [comment]
Hi,
I don't have seen such an error. But I had earlier such named queries, which begins with "~".
These were tmp-objects from access, I did delete it without side effects.

**Comment by MwaltmanFEI** [comment]
@Tanarri Thanks!  I agree the "~" indicates a temp object but I've been unable to find the temp objects to delete.  Any guidance on how you did it?

**Comment by mwolfe02** [comment]
Those queries with the leading tilde (~) typically represent literal SQL statements stored in the RecordSource properties of forms/reports or the RowSource properties of Combo/List box controls.  If you can identify the form or report where they are coming from, you may be able to do a `SaveAsText`/delete object/`LoadFromText` cycle on the object to clear out the query from whatever internal location it is being stored.

**Comment by hecon5** [comment]
@MwaltmanFEI is this still an issue? This may be similar to this (deleted SQL tables: #536), but not guaranteed. If it isn't, can you close the issue?
