### ISSUE TITLE
After rebuild, some controls are flat instead of 3D

### ISSUE THREAD

**Issue by HughWarrington** [joyfullservice/msaccess-vcs-addin#551]
I'm using addin version 4.0.34, Office 365 64-bit, Win10 64-bit.

I did a full export of my frontend .mdb. Then took the .src folder and ran a Build As....

In the imported frontend, the appearance of many controls has changed. Easiest shown with before:

![before](https://github.com/user-attachments/assets/4ca64171-d175-4d86-bdc1-09d3b07a707e)

After:

![after](https://github.com/user-attachments/assets/aa7876f3-ffc1-4eb9-b998-81898f6bc8da)

The buttons and combo boxes had a 3D or sunken appearance before. Now they have a 2D flat style. The textbox controls are unchanged, being 3D before and after.

There are two problems really:
1. It's changed.
2. It's changed inconsistently.

By which I mean, a consistent change from everything 3D to everything flat would at least be preferable to what has happened. Best would be no change at all.

Some extra info: I can restore the former appearance of the combo boxes in design view by selecting them, going to the 'Special Effect' property which is set to Sunken, setting this to Shadowed, then back to Sunken (!). I can find no way to restore the original 3D appearance of the buttons. It isn't manageable to apply this fix manually across the database since there are tens of forms and thousands of controls.

In the add-in options, choosing 'Extract Theme Files' didn't change the output. Also, I thought maybe it would help to set both of the sanitise options to Off. But this led to another couple of errors (which I will write up) so I couldn't complete an export/import cycle to see.

Any ideas?

Articles like [this](https://www.access-programmers.co.uk/forums/threads/command-button-styles.120737/) and [this](https://www.office-forums.com/threads/special-effect-is-unavailable-for-command-buttons.327406/) do not fill me with hope.

**Comment by hecon5** [comment]
Ok, so the fact you can correct this is interesting to me...because once I save as an `.mdb` file...it doesn't let me set any special effects on buttons in my setup. I am quite surprised they even show up as effects on your pre-export version, too!

I lost all abilities in Access to create buttons with any style other than flat with `.mdb` files. I also have Win 10, Office 365.

What I did: 

Started a form in Access. Added a control button, made it beveled, and colored. Saved as `.accdb`. Then saved as `.mdb`. 

As soon as I saved as an `.mdb` file, the special effects menu is all grayed out, and buttons on a test form were flattened; this is even before I did an export. The buttons also lost their colors.

See grayed out menus for buttons: 
![image](https://github.com/user-attachments/assets/9b3d6b14-5442-4175-9565-b97b0d6e87b1)

Same form, but saved as an ACCDB file: 
![image](https://github.com/user-attachments/assets/5ce390ff-7fea-4b0c-9d01-a7d4ea908348)

![image](https://github.com/user-attachments/assets/30113b4f-3dc8-421e-8910-77d3fb45c255)

**Comment by joyfullservice** [comment]
There are a couple properties to keep in mind when building from source...

![image](https://github.com/user-attachments/assets/03a96316-3db9-443b-bcb4-0ecf985580d0)

![image](https://github.com/user-attachments/assets/d33ac9c2-18b0-407d-a109-c24afc5a11d0)

The `FileFormat` property in `project.json` file will attempt to specify the database version when building from source.

![image](https://github.com/user-attachments/assets/73e83b1c-fd1d-4cc4-bde2-7a36b5492ddc)

**Comment by hecon5** [comment]
Yep; checked all those. As soon as I save as `.mdb` the buttons get flattened.

Also of note: I cannot apply a special effect to buttons, even in ACCDB files. I can apply them to textboxes and comboboxes, but not buttons. The buttons have a "bevel" effect on the shape effect: 
![image](https://github.com/user-attachments/assets/aeaa9fca-63f4-4241-a1f4-18ad0d64f410)


To get buttons w/ a sunken look, I had to apply the bevel effect.
![image](https://github.com/user-attachments/assets/83590de8-2f93-40ec-82cb-b05015c33ef9)

In MDB files, I cannot apply the bevel effect to buttons, but I can set the shape outline line thickness to very thick, which seems to create a sort of bevel look:
![image](https://github.com/user-attachments/assets/3b339048-7833-4202-9d82-0d4ee412cf24)
![image](https://github.com/user-attachments/assets/b6ecef4c-8486-4e25-a82a-51846b197084)

The buttons, as exported, look like this with sanitize on:

#### ACCDB:
```VBA
                Begin CommandButton
                    OverlapFlags =85
                    Left =10020
                    Top =840
                    Width =1320
                    Height =1140
                    TabIndex =5
                    Name ="Command19"
                    Caption ="Command12"
                    OnClick ="[Event Procedure]"

                    LayoutCachedLeft =10020
                    LayoutCachedTop =840
                    LayoutCachedWidth =11340
                    LayoutCachedHeight =1980
                    Bevel =3
                End
```


#### MDB
```VBA


```


and with sanitize off:

#### ACCDB

```VBA
                Begin CommandButton
                    OverlapFlags =85
                    Left =10020
                    Top =840
                    Width =1320
                    Height =1140
                    TabIndex =5
                    Name ="Command19"
                    Caption ="Command12"
                    OnClick ="[Event Procedure]"
                    GUID = Begin
                        0xeac814669efcd5428554bec6578f0603
                    End

                    LayoutCachedLeft =10020
                    LayoutCachedTop =840
                    LayoutCachedWidth =11340
                    LayoutCachedHeight =1980
                    Bevel =3
                    WebImagePaddingLeft =2
                    WebImagePaddingTop =2
                    WebImagePaddingRight =1
                    WebImagePaddingBottom =1
                End

```

**Comment by HughWarrington** [comment]
@joyfullservice you nailed it. In my case, the newly built frontend had `Use Windows-Themed Controls on Forms` checked, whereas the database original from which I exported did not. Unchecking that box in the import fixed things, i.e. returned the controls to the consistently 3D/sunken appearance they had before.

Is there a way to have that setting persisted in version control too? Looks like it would belong in dbs-properties.json.

**Comment by HughWarrington** [comment]
Actually, perhaps I could broaden that question to all the properties in the 'Current Database' options page. In my particular case it's the Navigation section and Ribbon and Toolbar Options that I want to persist.

**Comment by hecon5** [comment]
I think it is already exported in `dbs-properties.json` under `Themed Form Controls`; though the state appears to be inverted:

**Comment by hecon5** [comment]
> Actually, perhaps I could broaden that question to all the properties in the 'Current Database' options page. In my particular case it's the Navigation section and Ribbon and Toolbar Options that I want to persist.

`dbs-properties.json` carries all that info.

**Comment by hecon5** [comment]
> I think it is already exported in `dbs-properties.json` under `Themed Form Controls`; though the state appears to be inverted:

Eh, belay that, it's not inverted. But changing `Use Windows-Themed Controls on Forms` Exports as `Themed Form Controls`.

**Comment by hecon5** [comment]
(Sorry for spam)

So, are you saying @HughWarrington this value isn't persisted after you export/import?

**Comment by HughWarrington** [comment]
In the original database, under the Current Database options page, 'Use Windows-Themed Controls on Forms' is not ticked. When I run an export of that file, 'Themed Form Controls' does not appear in the resulting dbs-properties.json. When I build from the export, that button is ticked in the settings page for the new .mdb, resulting in a different appearance from the source.

**Comment by hecon5** [comment]
> In the original database, under the Current Database options page, 'Use Windows-Themed Controls on Forms' is not ticked. When I run an export of that file, 'Themed Form Controls' does not appear in the resulting dbs-properties.json. When I build from the export, that button is ticked in the settings page for the new .mdb, resulting in a different appearance from the source.

Hmm, that's interesting; if you go back to the original DB, check the box, save / reopen, uncheck the box save and export, does it show up? 

Reason being: I wonder if the original file didn't even have that option, so the property didn't exist when you exported. When you set/cleared it, the option showed up and thus is exported. When I export it shows up, but I started this file on this version of Access, so it likely existed from the file onset (and thus was exported).

**Comment by HughWarrington** [comment]
> Actually, perhaps I could broaden that question to all the properties in the 'Current Database' options page. In my particular case it's the Navigation section and Ribbon and Toolbar Options that I want to persist.

Note to self: here's a reference for all of those named properties: https://learn.microsoft.com/en-us/office/vba/access/concepts/settings/set-options-from-visual-basic

**Comment by HughWarrington** [comment]
@hecon5

> if you go back to the original DB, check the box, save / reopen, uncheck the box save and export, does it show up?

Yes! And thereafter, `Themed Form Controls` appears in dbs-properties.json every time, whether or not the box is checked in the options page. Thanks :)

**Comment by HughWarrington** [comment]
From my perspective I'm happy to close this ticket now. Not sure whether @hecon5 raised the same issue or something different above.

**Comment by hecon5** [comment]
@HughWarrington go ahead and close it, the issue I experienced was a related issue but turned out to not matter for me. If I run into it again I can create a new instance.
