### ISSUE TITLE
Non-ASCII characters import incorrectly from XML table data exports

### ISSUE THREAD

**Issue by mwolfe02** [joyfullservice/msaccess-vcs-addin#560]
This appears to be a side effect of issue #217.

I have some local tables with embedded non-ASCII characters (e.g., the trademark character: `™`). 

When I export to source, the characters are initially saved correctly.  However, when the exported file is loaded for sanitizing, it gets imported as a Windows-1252-encoded file, which results in the characters being converted from valid Unicode characters into the Windows-1252 encoding.

### clsDbTableData.IDBComponent.Export()
```
                    With New clsSourceParser
                        .LoadSourceFile strFile   ' <-- This line is where the problem starts
                        WriteFile .Sanitize(ectXML), strFile
                    End With
```

### modVCSUtility.ReadSourceFile

The true culprit appears to be the `modVCSUtility.ReadSourceFile` function.  This section in particular appears to cause the problem:
```
            If DbVersion <= 4 Then
                ' Access 2000 format exports using system codepage
                ' See issue #217
                ReadSourceFile = ReadFile(strPath, GetSystemEncoding)
            Else
                ' Newer versions export as UTF-8
                ReadSourceFile = ReadFile(strPath)
            End If
```

The source database application is an .mdb, so the `DbVersion` is `4`.  That causes the `ReadFile()` function to be passed the system encoding, which--in my case--is `Windows-1252`.

**Comment by hecon5** [comment]
One way to handle this is to use `Options.Upgrade` to add a key such as `XMLLegacyOut` or something, which will then import the file as-is until it's been exported; once this happens the import `ReadSourceFile` will import as shown above. We'd need to add `And Options.XMLLegacyOut` to the `If` statement you have here, but that would ensure the exported "mangled" files look the same. 

All that said: if the file is already mangled, I don't know if that'll help, because it's already "corrupted". Perhaps if it is corrupted, keeping it that way will make it easier to detect than not.

Thoughts?

**Comment by joyfullservice** [comment]
Thanks for pointing out this issue! Let me see if I can do a little testing on my end to recreate the issue and see if we can get a good solution in place. I like the idea of keeping the source files consistently in UTF-8, as that is the most portable format across different system locales, but we definitely need to use care when importing data to ensure we are parsing it correctly.

**Comment by joyfullservice** [comment]
@mwolfe02 - After testing this out, I think your approach is a great way to handle this. `Application.ExportXML` produces UTF-8 [by default](https://learn.microsoft.com/en-us/office/vba/api/access.application.exportxml), so I think we are pretty safe to assume that _**any**_ XML source file is going to be in this format, regardless of the database version.  👍
