### ISSUE TITLE
Crash when exporting using Database Option

### ISSUE THREAD

**Issue by ronmcca** [joyfullservice/msaccess-vcs-addin#563]
The export failed because of a connection string error when I added the database option.
clsScemaMsSql
   lDbScema
      Export

Error Line: If (m_ModifiedItems.Count = 0) And (m_Files.Count = m_AllItems.Count) Then

Adding a test for m_ModifiedItems is Nothing got it past the line

    If m_ModifiedItems Is Nothing Then
        
    ElseIf (m_ModifiedItems.Count = 0) And (m_Files.Count = m_AllItems.Count) Then

**Comment by joyfullservice** [comment]
If you click the link to test the filter, do you get a number of objects returned?

![image](https://github.com/user-attachments/assets/9638cb72-d913-4239-b23f-74a34bb9e6ec)

When you say a connection string error, do you mean that your system is unable to connect to the database? We can probably add some additional error handling around this, but it would be helpful to understand more about the issue you are experiencing.

**Comment by ronmcca** [comment]
With the correct connection sting, I get the correct count.

Once I have exported database, I can’t reproduce the error.

  1.  I removed the database from the options,
  2.  Export
  3.  Remove the Database folder from the export.
  4.  Add back the database option with the incorrect connection string.
  5.  Test give me the following error message. ***@***.***
  6.  Export, I get the following error ***@***.***

With my modifications, the system reports unable to connect.


Thank you,

Ron McCarry
It Manager
Pack Air Inc.
Leave Testimonial<https://g.page/r/CehZz65pBzwFEBM/review>  |  Blog<https://packairinc.com/blog/>
***@***.***>  |  LinkedIn<https://www.linkedin.com/company/pack-air-inc-/>  |  Website<https://www.packairinc.com/>

**Comment by joyfullservice** [comment]
> I included screen shots but then did not show. 

_Just a tip, but if you are on the GitHub web page for this issue, you can paste a screen shot image directly into the comment and it will automatically generate the image file and link it for you. That's what I do most of the time when I need to include a screen shot._

Maybe I am missing something obvious here, ...but why are you removing the database connection and putting in an invalid connection string? Or are you just demonstrating that it doesn't handle the error very gracefully if the connection string is invalid?

If you can elaborate a bit more on what you are wanting to do, or what you expect the intended behavior to be, that will help me know better how to help.  😄

**Comment by ronmcca** [comment]
I got it to work with a corrected connection string. But to duplicate the error and answer your questions, I removed the database information and deleted the exported folder. 
It looks like it fails on the 1st try if the connection string is wrong.

**Comment by joyfullservice** [comment]
Gotcha. So I am understanding that the goal here would be to do a better job of handling the error if the connection string is invalid or cannot connect to the database?

I am leaning towards a non-critical error if the database cannot be accessed. There might be cases where you are doing off-line development in another part of the database, and you would still like the rest of the export to complete normally, even if the remote database cannot be accessed.

**Comment by ronmcca** [comment]
It did stop the export and opened the VBA editor to the offending line which made it easy to figure out the problem. The fix I tried allowed the system to output the connection problem to message box and continued the export.

Once the remote database is exported, any future connection problem reports the error and continues the export.

**Comment by joyfullservice** [comment]
Digging into this a bit further, this is something that should be resolved through the following issue and related pull request:
- #546 
- #547

**Comment by ronmcca** [comment]
So it looks like it will be fixed in a future release.
