### ISSUE TITLE
Version Control Menu Option disappeared.

### ISSUE THREAD

**Issue by jeffdombach** [joyfullservice/msaccess-vcs-addin#564]
The Version Control option disappeared from my menu. When I check Add-Ins, it is available to be installed. When I click Install, I get an error "The add-in could not be installed because it is missing a USysRegInfo table."

**Comment by joyfullservice** [comment]
This add-in has built-in installer, which you can run by downloading and opening the add-in file. The Access add-ins that you were looking at is a different way to install add-ins, and not compatible with this particular add-in.

You can find installation instructions [on the wiki](https://github.com/joyfullservice/msaccess-vcs-addin/wiki/Installation).

Hope that helps!

**Comment by jeffdombach** [comment]
I re-ran the built in installer and it is still missing from the menu.

Jeff Dombach
717.314.3792

On Nov 21, 2024, at 12:07 PM, Adam Waller ***@***.***> wrote:

﻿

This add-in has built-in installer, which you can run by downloading and opening the add-in file. The Access add-ins that you were looking at is a different way to install add-ins, and not compatible with this particular add-in.

You can find installation instructions on the wiki<https://github.com/joyfullservice/msaccess-vcs-addin/wiki/Installation>.

Hope that helps!

**Comment by jeffdombach** [comment]
I had installed several months and I absolutely love using. I see the COM Add-In. When I click the checkbox and restart Access, still no sign of VCS in the menu. Using Version_Control_v4.0.34.zip

![image](https://github.com/user-attachments/assets/380b4132-71b6-4674-9be3-fcba5376ebfe)

**Comment by joyfullservice** [comment]
Hmm... I don't have that version of Access to test, but maybe we could try manually removing the add-in files, and reinstalling. It is also possible that an Access "update" broke something, but hopefully not...  🤔 

To manually remove the files, you can press <kbd>WIN</kbd>+<kbd>R</kbd> and enter `%appdata%` in the box. Click run, then navigate to the `MSAccessVCS` folder and delete the following files:

- `Version Control.accda`
- `MSAccessVCSLib_win64.dll`
- `Ribbon.xml`

Then run the install again, (making sure you have extracted the add-in from the zip file) and see if that fixes it.

If that still doesn't fix it, (but the files are installed in the correct location) then you can use another method to load the add-in. (The goal here is to get to the options screen so we can run the uninstall, which will remove DLL registrations and other registry entries as well for a clean uninstall.)

Paste the following into a standard module in any database, and run the function.

```vba
Public Function ExampleLoadAddInAndShowOptions()

    Dim strAddInPath As String
    Dim proj As Object      ' VBProject
    Dim objAddIn As Object  ' VBProject

    ' Build default add-in path
    strAddInPath = Environ$("AppData") & "\MSAccessVCS\Version Control.accda"

    ' See if add-in project is already loaded.
    For Each proj In VBE.VBProjects
        If StrComp(proj.FileName, strAddInPath, vbTextCompare) = 0 Then
            Set objAddIn = proj
        End If
    Next proj

    ' If not loaded, then attempt to load the add-in.
    If objAddIn Is Nothing Then

        ' The following lines will load the add-in at the application level,
        ' but will not actually call the function. Ignore the error of function not found.
        ' https://stackoverflow.com/questions/62270088/how-can-i-launch-an-access-add-in-not-com-add-in-from-vba-code
        On Error Resume Next
        Application.Run strAddInPath & "!DummyFunction"
        On Error GoTo 0

        ' See if it is loaded now...
        For Each proj In VBE.VBProjects
            If StrComp(proj.FileName, strAddInPath, vbTextCompare) = 0 Then
                Set objAddIn = proj
            End If
        Next proj
    End If

    If objAddIn Is Nothing Then
        MsgBox "Unable to load Version Control add-in. Please ensure that it has been installed" & vbCrLf & _
            "and is functioning correctly. (It should be available in the Add-ins menu.)", vbExclamation
    Else
        ' Launch add-in and show options
        Application.Run "MSAccessVCS.HandleRibbonCommand", "btnShowOptions"
    End If

End Function
```

If the options window loads, then click the button to uninstall the add-in.

![image](https://github.com/user-attachments/assets/aaf84228-4dde-4192-b9f8-d25e5a694c65)

After this, try installing again and see if it works normally after that.

**Comment by jeffdombach** [comment]
Finally got back to this.

When I run the function I get the following message.
![image](https://github.com/user-attachments/assets/59458f31-f6f6-4bbe-8544-3054524ee48f)

**Comment by jeffdombach** [comment]
I started Access and then went to open Version Control.accda and got this screen
![image](https://github.com/user-attachments/assets/63804220-398c-4243-ba83-381ce1ade741)

Went thru a couple more steps, and SUCCESS! Wish I remember the exact steps.

**Comment by joyfullservice** [comment]
Yay!! I am glad to hear it is working for you again!

I don't know if it was one of the steps involved, but in some more secured environments, there is an additional checkbox under advanced options that can give you the opportunity to trust the add-in file after installing it. Most installations don't seem to need this, but there are some environments where it seems necessary.

![image](https://github.com/user-attachments/assets/4cf90cf8-99e0-4894-a32e-3e49f59560dd)

**Comment by jeffdombach** [comment]
Thank you for your help and persistence. Hopefully it is beneficial for you too.

________________________________

**Comment by joyfullservice** [comment]
I will go ahead and close this out, but feel free to reopen if there is anything specific that we need to address in the add-in.
