### ISSUE TITLE
Missing a USysRegInfo table

### ISSUE THREAD

**Issue by OldGuy1949** [joyfullservice/msaccess-vcs-addin#569]
Attempting to install latest version, quote from Add-In Manager: "The add-in could not be installed because it is missing a USysRegInfo table.  I'm brand new to the version control system.
During install dialog, I changed the target directory to my working directory, which is not on C:.
The Add-In Manager identifies the add-n as https://github.com/joyfullservice/msaccess-vcs-addin
I will remove the package and try again.
Any advice?

**Comment by joyfullservice** [comment]
You won't need to use the add-on manager to install it. It has a built-in installer that works much better and doesn't require any extra privileges. Check out https://github.com/joyfullservice/msaccess-vcs-addin/wiki/Quick-Start for some more tips.

Hope that helps!

**Comment by OldGuy1949** [comment]
The issue is resolved.  I removed the software and rebooted the machine.  Did the install again, this time using a Windows standard path: C:\Users\ME\... instead of where I tried the install the first time, E:\ME\special-place.  I do see the VCS database and it's parts in the directory "E:\ME\DATABASES\..." where my working databases are.  Kind of messy with the .dl and .XML file there.  I'll get over it.
Consider this case closed - newbie error.

**Comment by joyfullservice** [comment]
Just as an additional tip, the default installation path is `{AppData}\MSAccessVCS` which typically translates to something like `C:\Users\MyUserName\AppData\Roaming\MSAccessVCS`. This keeps all the add-in files nicely tucked away in a standard location in Windows. The only time I would advise changing the install path is if you have unique security requirements that don't allow read/write access to that folder, or restricted privileges that keep the add-in from running.

For 99% of users, the standard install path should work with no issues, and you won't have the add-in files getting mixed into the project areas. The wiki describes various options related to the export path, which is another area that is sometimes confusing for new users. For most people I recommend leaving the default option which exports the source files into a subfolder under the database project folder.

**Comment by OldGuy1949** [comment]
Can I un-install (remove?) the XML DLL and database and try to install again?  If so, is the database the repository for the versioning information?  We keep our data somewhere other than C:\[anything].  If the XML DLL and database are simply software, I'll happily leave them in the C drive.

**Comment by joyfullservice** [comment]
The install involves files and registry entries, so I would recommend using the built-in uninstall (on the options page), then clean up any remaining files. Then when you run the reinstall, you can check the advanced tab, just to make sure it is installing in the default location.

![image](https://github.com/user-attachments/assets/f6251788-7845-4795-853d-be56befdcb39)

This add-in is technical a database developed in Microsoft Access, but it is not the repository for version control for your database project. It is simply a tool that exports all the components of your database project into text files that you can use in the version control software of your choice. (i.e. Git, Subversion, Mercurial, etc...) Mike Wolfe [describes this](https://nolongerset.com/version-control-add-in-purpose/) as a bridge between Microsoft Access and version control.

Let me know if you have any more specific questions!
