### ISSUE TITLE
Minor change to QuickStart instructions

### ISSUE THREAD

**Issue by jhgarrison** [joyfullservice/msaccess-vcs-addin#571]
After "Download latest release", replace "Extract and open `Version Control.accda` from the zip archive." with

- Extract `Version Control.accda` from the zip archive to a location that is trusted by MS Access, or add the download folder to the list of trusted locations.
- Open `Version Control.accda`

**Comment by joyfullservice** [comment]
Good idea, thanks! I have updated the Quick Start with an additional note.
